# Generated by Django 3.1.3 on 2020-11-18 21:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201116_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
